### ISSUE TITLE
Organisationsnummer?

### ISSUE THREAD

**Issue by stnor** [girgen/skolschema#10]
Jag tycker det vore lämpligt att organisationsnummer finns på Organisation ("Huvudman").
Hur är det tänkt att funka. Det framgår varken från standarden eller exemplen.

I vårt system är primärnyckel för licensinnehavare orgnr.

**Comment by stnor** [comment]
Sedan finns inte relationen till Organisation i exemplen för SchoolUnit

**Comment by girgen** [comment]
Det stämmer att det saknas i POST-exemplet. Tack!

**Comment by stnor** [comment]
Det är även en del exempel som hänvisar till schema 2.0 istf 1.0 om det nu ska vara enl gällande standard.

**Comment by stnor** [comment]
Exempel:
urn:ietf:params:scim:schemas:core:2.0:SchoolUnit
borde väl vara 
urn:scim:schemas:extension:sis:school:1.0:SchoolUnit ?
````
  {
    "schemas": [
      "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
    ],
    "id": "SchoolUnit",
    "name": "SchoolUnit",
    "endpoint": "/SchoolUnits",
    "description": "SchoolUnit",
    "schema": "urn:ietf:params:scim:schemas:core:2.0:SchoolUnit",
    "meta": {
      "location": "/v2/ResourceTypes/SchoolUnit",
      "resourceType": "ResourceType"
    }
  },
  {
    "schemas": [
      "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
    ],
    "id": "StudentGroup",
    "name": "StudentGroup",
    "endpoint": "/StudentGroups",
    "description": "StudentGroup",
    "schema": "urn:ietf:params:scim:schemas:core:2.0:StudentGroup",
    "meta": {
      "location": "/v2/ResourceTypes/StudentGroup",
      "resourceType": "ResourceType"
    }
  },
  {
    "schemas": [
      "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
    ],
    "id": "Activity",
    "name": "Activity",
    "endpoint": "/Activities",
    "description": "Activity",
    "schema": "urn:scim:schemas:extension:sis:school:1.0:Activity",
    "meta": {
      "location": "/v2/ResourceTypes/Activity",
      "resourceType": "ResourceType"
    }
  },
````

**Comment by girgen** [comment]
Organisation har inte organisationsnummer i version 1. Det får läggas till out-of-band. Vi tittar på att utöka organisation med organisationsnummer i version 2.

Exempel på organisation och länk från SchoolUnit är tillagda. Tack!
