### ISSUE TITLE
Det framgår inte om en relation är $ref eller inline och exempel är felaktiga

### ISSUE THREAD

**Issue by stnor** [girgen/skolschema#11]
Jag anser att standarden måste specificera om fältet är inlined eller referens i respektive relation, fast det kan ju bero på att jag inte vet så mycket om SCIM?

Exempel:
Enligt standarden ska Enrolment ett "enrolledAt"-attribut.

Enligt detta exempel har enrolement schoolUnitId
https://github.com/stnor/skolschema/blob/master/exempel/user-student-get.json#L84

Det framgår inte av varken exempel eller standard om enrolledAt är $ref eller ej.

**Comment by stnor** [comment]
Jag antar att "enrolledAt" är en felaktighet i wordfilen och diagrammet. Övrigt framgår av schemat.

**Comment by girgen** [comment]
Det stämmer att schemat är korrekt. Detta är en begränsning i hur SCIM fungerar, att referenser ska nämnas med $ref. I vissa fall blir det lite olyckligt i överföringen från domänmodellen till SCIM. Det kommer bli tydligare i version 2 av SS12000. Stänger detta ärendemed hänvisning till version 2.
