### ISSUE TITLE
Schemafilerna verkar inte stämma med standarden i någon branch.

### ISSUE THREAD

**Issue by stnor** [girgen/skolschema#14]
Jag kan inte se att någon version av schemafilerna stämmer med standardens ER-diagram (ex User).

Kan man förutsätta att schemafilerna i v1-branchen gäller som interop-modell?

**Comment by girgen** [comment]
Hej Stefan!

Allt finns i den publicerade standarden. Där är det taggen 1.0 som är publicerad.

Palle

**Comment by stnor** [comment]
Tack.
