### ISSUE TITLE
Federation entityId på Organisation?

### ISSUE THREAD

**Issue by stnor** [girgen/skolschema#16]
Efter att ha jobbat en del med autenticering så tänker jag att det vore fint med ett optional-fält på Organisation för federationEntityId som motsvarar fältet ["entity_id" i metadatat](https://github.com/kirei/scim-fed-auth/blob/7182f48c6bc6834b5854344f8317d72aee864c51/example.json#L4) för organisationen.

Kan det vara något för standarden?

**Comment by girgen** [comment]
Det blir lite knepigt om man blandar in auktorisering i informationsmodellen. Vad skulle det i praktiken användas till?

**Comment by stnor** [comment]
Du har rätt. Dålig idé. Vi gör detta internt av lite olika anledningar, behöver inte vara i specen.
