### ISSUE TITLE
StudentGroup "display" borde vara "displayName" för att vara konsekvent

### ISSUE THREAD

**Issue by stnor** [girgen/skolschema#17]
Hej!
Borde inte StudentGroup-fältet heta "displayName" som i Scim-standarden?
Avviker i schema och exempel

**Comment by girgen** [comment]
SCIM är inte konsekventa med "displayName", men det *låter* rimligt. Jag måste kolla och återkomma.

**Comment by stnor** [comment]
Både i ScimUser och i ScimGroup heter det "displayName"
