### ISSUE TITLE
booleanfältet i Employment "isTeacher" ska tas bort ur exempel

### ISSUE THREAD

**Issue by stnor** [girgen/skolschema#18]
Booleanfältet i Employment "isTeacher" borde vara "teacher" på samma sätt som t ex "active" i ScimUser inte heter "isActive"

**Comment by stnor** [comment]
Eller tas bort? Det är ju redundant med employmentRole och  "isTeacher".
jag ser nu att "isTeacher" inte finns i schemat, men i exemplet.

**Comment by girgen** [comment]
Tack! Det stämmer att isTeacher ska bort.
