### ISSUE TITLE
Varför är schoolYear i enrolement immutable?

### ISSUE THREAD

**Issue by stnor** [girgen/skolschema#20]
Man måste väl kunna göra en PUT när det gått ett år och eleven går i en ny årskurs på samma skola?

**Comment by stnor** [comment]
Jag förstår tanken.
Det kändes som Egil-projektets bild var att det endast skulle synkas aktuellt data och att därmed startDate och endDate inte är jätteintressanta. Och därmed går det ju då inte att se vilken enrolement som är aktiv det fallet.

**Comment by stnor** [comment]
Sedan är det väl högst tveksamt om det affärsmässigt är att betrakta som en ny inskrivning när man byter årskurs.

**Comment by girgen** [comment]
> Det kändes som Egil-projektets bild var att det endast skulle synkas aktuellt data och att därmed startDate och endDate inte är jätteintressanta. Och därmed går det ju då inte att se vilken enrolement som är aktiv det fallet.
Då följer Egil inte standarden, den kräver datum. Det verkar dessutom vara en onödig förenkling, det kan inte vara svårt att generalisera till hela läsåret om man inte har informationen tillgänglig.


> Sedan är det väl högst tveksamt om det affärsmässigt är att betrakta som en ny inskrivning när man byter årskurs.

Well, det är inte en _ny inkrivning_ per se, det är en ny rad som visar hur inskrivningen förändras över tid.

**Comment by stnor** [comment]
Hej Palle!
Tack för svaren.

Man kan ju välja att se det som att Egil inte följer standarden. Det var ju därför en av de första sakerna jag föreslog var att ha olika "profiles" på standarden.

Nu är ju syftet med Egil så vitt jag förstår att se till att läromedelsleveratörerna har AKTUELL data, och därmed att objekt som inte längre är relevant skall gallras/tas bort.

Jag kan förstå att det finns andra områden för SS12000, där ditt resonemang av behova av historik måste tillgodoses.

**Comment by stnor** [comment]
> Well, det är inte en _ny inkrivning_ per se, det är en ny rad som visar hur inskrivningen förändras över tid.

Inte för att det det spelar någon roll, med varför finns då bara detta resonemeng här, och inte för andra attributförändringar, mer genomgående?

**Comment by girgen** [comment]
> > Well, det är inte en _ny inkrivning_ per se, det är en ny rad som visar hur inskrivningen förändras över tid.
> 
> Inte för att det det spelar någon roll, med varför finns då bara detta resonemang här, och inte för andra attributförändringar, mer genomgående?

Mmm, det finns ju genomgående för de typer av data där det är viktigt, för de processer som stöds, att  ha koll på förändringar över tid. Attribut har sällan en sån egenskap, men en del relationer har det, som gruppmedlemsskap och andra grupprelationer samt exempelvis inskrivningar.

**Comment by girgen** [comment]
Jag stänger denna, öppna gärna om du hittar några objekt där mitt resonemang ovan inte stämmer.
