### ISSUE TITLE
I exemplen ska securityMarking vara boolean, inte string

### ISSUE THREAD

**Issue by p-blomberg** [girgen/skolschema#9]
I exempel/user-post.json och exempel/user-student-post.json finns följande rad med:
`"securityMarking": "false",`

Visst ska väl detta vara en boolean och inte en sträng? Det vill säga:
`"securityMarking": false,`

Samma fel finns även med i SS12000:2018 (publicerad 2018-02-05). På sidan 14 framgår att securityMarking ska vara boolean, men exemplet på sidan 33 använder en sträng.

**Comment by girgen** [comment]
Hej!

Det låter rimlgit. Jag ska kolla med gruppen när vi träffas nästa vecka.
